version: "3.8"
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: muxi202507
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    ports:
      - "5432:5432"
    restart: always

  app:
    build: .
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PASSWORD=123456
      - DB_NAME=muxi202507
    ports:
      - "8080:8080"
    restart: always